In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Combining Datasets

First starting with Acquisition and Performance data

In [2]:
AcquisitionColumnNames = (
    "LOAN_ID", "ORIG_CHN", "Seller.Name", 
    "ORIG_RT", "ORIG_AMT", "ORIG_TRM", "ORIG_DTE",
    "FRST_DTE", "OLTV", "OCLTV", "NUM_BO", 
    "DTI", "CSCORE_B", "FTHB_FLG", "PURPOSE", 
    "PROP_TYP", "NUM_UNIT", "OCC_STAT", "STATE", "ZIP_3", 
    "MI_PCT", "Product.Type", "CSCORE_C", "MI_TYPE", 
    "RELOCATION_FLG"
)

PerformanceColumnNames = (
    "LOAN_ID", "Monthly.Rpt.Prd", "Servicer.Name", 
    "LAST_RT", "LAST_UPB", "Loan.Age", "Months.To.Legal.Mat", 
    "Adj.Month.To.Mat", "Maturity.Date", "MSA", 
    "Delq.Status", "MOD_FLAG", "Zero.Bal.Code", 
    "ZB_DTE", "LPI_DTE", "FCC_DTE","DISP_DT", 
    "FCC_COST", "PP_COST", "AR_COST", "IE_COST", 
    "TAX_COST", "NS_PROCS","CE_PROCS", "RMW_PROCS", 
    "O_PROCS", "NON_INT_UPB", "PRIN_FORG_UPB_FHFA", 
    "REPCH_FLAG", "PRIN_FORG_UPB_OTH", "TRANSFER_FLG"
)

In [3]:
# Data path will change depending on your system setup.

acquisition_data_path = "C:/Users/krish/Desktop/Preety/Acquisition_2010Q1.txt"

performance_data_path = "C:/Users/krish/Desktop/Preety/Performance_2010Q1.txt"

acquisition_df = pd.read_csv(
    acquisition_data_path,
    names=AcquisitionColumnNames,
    header=None,
    sep="|"
)

performance_df = pd.read_csv(
    performance_data_path,
    names=PerformanceColumnNames,
    header=None,
    sep="|"
)

C:\Users\krish\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (14,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

# Getting Initial Forclosure Data

In [4]:
FCC_DTE = performance_df['FCC_DTE'].notna()

forclosed = performance_df[FCC_DTE]

FORCLOSED = set(forclosed['LOAN_ID'])

def mapper(row):
    return row['LOAN_ID'] in FORCLOSED

acquisition_df['FCC'] = acquisition_df.apply(mapper, axis=1)

In [5]:
print(f"There are {len(FORCLOSED)} foreclosures!")

There are 93 foreclosures!

# Exploring Delq.Status

In [6]:
DELQ = performance_df['Delq.Status']
delq = set(DELQ)
print(delq)

{nan, '62', '14', '11', '0', '21', '13', '8', '59', '10', '4', '27', '42', '7', '35', '61', '22', '28', '41', '60', '57', '32', '50', '36', '45', '49', '54', 'X', '53', '12', '55', '43', '17', '24', '44', '34', '5', '6', '56', '47', '30', '39', '16', '20', '1', '3', '33', '40', '48', '52', '58', '63', '18', '38', '31', '64', '46', '15', '25', '66', '51', '23', '65', '19', '29', '2', '9', '37', '26'}

PART (a)

In [7]:
def delinqu_mapper(row):
    if row ['Monthly.Rpt.Prd']=="03/01/2014":
        return True
    return False

In [8]:
performance_df['correct_month']= performance_df.apply(delinqu_mapper, axis=1)
Monthly_Prd= performance_df[performance_df["correct_month"]]

In [9]:
Monthly_Prd

,LOAN_ID,Monthly.Rpt.Prd,Servicer.Name,LAST_RT,LAST_UPB,Loan.Age,Months.To.Legal.Mat,Adj.Month.To.Mat,Maturity.Date,MSA,...,NS_PROCS,CE_PROCS,RMW_PROCS,O_PROCS,NON_INT_UPB,PRIN_FORG_UPB_FHFA,REPCH_FLAG,PRIN_FORG_UPB_OTH,TRANSFER_FLG,correct_month
62,100013622306,03/01/2014,NaN,4.750,68259.31,50,130,129.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
180,100022098429,03/01/2014,NaN,5.250,432083.23,49,311,311.0,02/2040,35620,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
383,100032715932,03/01/2014,NaN,5.375,89716.43,51,309,308.0,12/2039,43340,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
444,100033339771,03/01/2014,NaN,5.250,281467.05,48,312,312.0,03/2040,14260,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
498,100036162795,03/01/2014,NaN,4.625,4872.09,50,130,4.0,01/2025,47900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
575,100040783841,03/01/2014,NaN,4.750,239547.32,49,311,311.0,02/2040,39340,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
685,100044567305,03/01/2014,NaN,4.875,87435.60,49,311,284.0,02/2040,36780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
763,100046088905,03/01/2014,NaN,4.750,259577.95,50,310,309.0,01/2040,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
831,100049953168,03/01/2014,NaN,5.250,272893.09,49,311,309.0,02/2040,35620,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
1012,100056508170,03/01/2014,NaN,5.000,132091.84,49,311,311.0,02/2040,47900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
1123,100056554242,03/01/2014,NaN,4.375,235293.39,50,130,130.0,01/2025,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
1224,100057102292,03/01/2014,NaN,5.125,93828.20,49,191,189.0,02/2030,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
1333,100061403984,03/01/2014,NaN,5.125,617866.42,49,311,311.0,02/2040,14860,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
1416,100064110478,03/01/2014,NaN,5.625,105948.73,47,313,242.0,04/2040,19100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
1483,100064988434,03/01/2014,NaN,4.875,280044.97,49,311,311.0,02/2040,38060,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
1552,100067986742,03/01/2014,NaN,4.375,318949.47,49,311,309.0,02/2040,14500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
1705,100080406480,03/01/2014,NaN,5.375,373113.46,49,311,307.0,02/2040,41620,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
1756,100080816876,03/01/2014,NaN,4.875,27533.76,49,191,189.0,02/2030,32820,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
1878,100091653134,03/01/2014,NaN,5.375,291503.48,50,310,308.0,01/2040,34060,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
1988,100102705096,03/01/2014,NaN,5.400,247798.84,49,311,311.0,02/2040,16820,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
2097,100106628052,03/01/2014,NaN,4.875,210966.93,49,311,311.0,02/2040,26420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
2147,100106720992,03/01/2014,NaN,4.500,118681.22,49,131,129.0,02/2025,16940,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
2400,100115404605,03/01/2014,NaN,4.875,56009.33,49,311,311.0,02/2040,43340,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
2633,100123724633,03/01/2014,NaN,4.990,56928.19,50,310,310.0,01/2040,12060,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
2781,100125687921,03/01/2014,NaN,5.250,175181.20,50,310,310.0,01/2040,31140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
2890,100128733361,03/01/2014,NaN,5.310,70512.92,49,311,295.0,02/2040,32820,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
3028,100131470452,03/01/2014,NaN,4.875,188495.33,48,312,311.0,03/2040,31100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
3119,100140736549,03/01/2014,NaN,4.375,131693.47,50,130,130.0,01/2025,45300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
3250,100147536304,03/01/2014,NaN,4.875,375819.55,49,311,310.0,02/2040,41740,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
3324,100148922070,03/01/2014,NaN,4.875,140006.79,49,311,303.0,02/2040,19820,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996824,149008921649,03/01/2014,NaN,4.375,231371.22,49,131,130.0,02/2025,35620,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
996927,149014097158,03/01/2014,NaN,4.750,236074.13,49,311,296.0,02/2040,39300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
997000,149017940135,03/01/2014,NaN,4.375,23634.67,49,131,30.0,02/2025,12940,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
997057,149018477728,03/01/2014,NaN,5.250,115414.52,50,310,310.0,01/2040,18140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
997146,149020310708,03/01/2014,NaN,4.875,163096.93,50,310,310.0,01/2040,33100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
997292,149027541444,03/01/2014,NaN,5.000,68401.30,48,312,291.0,03/2040,19100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
997384,149028349873,03/01/2014,NaN,4.750,208438.06,50,310,280.0,01/2040,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
997453,149031998678,03/01/2014,NaN,4.500,109935.92,50,130,124.0,01/2025,35620,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
997563,149032075808,03/01/2014,NaN,5.000,240022.24,50,310,308.0,01/2040,39300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
997632,149033095798,03/01/2014,NaN,4.875,451133.84,49,311,311.0,02/2040,41740,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
997693,149036788984,03/01/2014,NaN,4.375,94658.72,49,131,131.0,02/2025,36540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
997767,149038279720,03/01/2014,NaN,5.375,56229.87,49,311,310.0,02/2040,40140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
997842,149038573413,03/01/2014,NaN,5.250,47865.95,49,311,300.0,02/2040,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
997965,149061282820,03/01/2014,NaN,5.000,104805.39,51,309,297.0,12/2039,41180,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
998058,149062046876,03/01/2014,NaN,4.875,198672.19,50,310,303.0,01/2040,12060,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
998168,149066543812,03/01/2014,NaN,5.000,141825.99,50,310,310.0,01/2040,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
998279,149073021946,03/01/2014,NaN,4.875,52584.01,50,190,190.0,01/2030,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
998572,149104482849,03/01/2014,NaN,4.625,116710.58,50,130,128.0,01/2025,16980,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
998675,149105435514,03/01/2014,NaN,4.875,194598.15,50,310,310.0,01/2040,16980,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
998817,149113864430,03/01/2014,NaN,4.250,114312.57,51,69,67.0,12/2019,45940,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
998960,149132541599,03/01/2014,NaN,4.375,158429.51,50,130,119.0,01/2025,41940,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
999062,149138031580,03/01/2014,NaN,4.625,86636.88,50,130,130.0,01/2025,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
999169,149142918034,03/01/2014,NaN,5.000,79893.10,49,311,280.0,02/2040,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
999280,149142995044,03/01/2014,NaN,5.375,187513.47,49,311,311.0,02/2040,27140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
999370,149145441898,03/01/2014,NaN,5.000,226482.78,50,310,282.0,01/2040,22520,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
999529,149162653642,03/01/2014,NaN,4.250,141524.03,50,130,103.0,01/2025,14860,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
999630,149170823980,03/01/2014,NaN,5.000,190132.81,50,310,310.0,01/2040,19100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
999693,149171575167,03/01/2014,NaN,4.875,97540.91,49,311,310.0,02/2040,25540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
999802,149175953968,03/01/2014,NaN,5.500,68230.66,48,312,313.0,03/2040,16980,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True
999953,149179972416,03/01/2014,NaN,5.250,132741.26,48,312,311.0,03/2040,40380,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,True

In [10]:
DEL_NOTNAN = performance_df["Delq.Status"].notna()
del_df = performance_df[DEL_NOTNAN]
print(f"There are {len(del_df.index)} Not NANS")

There are 999903 Not NANS

In [11]:
print(f"In Total: {len(performance_df.index)}")

In Total: 1000000

In [12]:
X = np.unique(del_df['Delq.Status'], return_counts=True)

In [13]:
Obj, Cnts = X

In [14]:
for obj, count in zip(Obj, Cnts):
    print(obj, count)

0 973170
1 6817
10 191
11 154
12 117
13 111
14 91
15 88
16 80
17 72
18 57
19 56
2 1575
20 46
21 44
22 46
23 37
24 30
25 30
26 29
27 29
28 30
29 24
3 712
30 25
31 19
32 16
33 14
34 13
35 13
36 11
37 13
38 10
39 12
4 483
40 9
41 10
42 9
43 8
44 7
45 7
46 7
47 7
48 7
49 7
5 403
50 7
51 6
52 12
53 6
54 6
55 3
56 2
57 2
58 2
59 1
6 356
60 1
61 1
62 1
63 1
64 1
65 2
66 2
7 283
8 258
9 198
X 14006


PART(b)- Adding new column 'Delinquency Status' to the Acquisitions dataframe

In [15]:
#acq_df_trimed = acquisition_df[Monthly_Prd["LOAN_ID"] == acquisition_df["LOAN_ID"]]

In [16]:
last_id = int(performance_df["LOAN_ID"][-1:])

In [17]:
acquisition_df.loc[last_id == acquisition_df["LOAN_ID"]]

,LOAN_ID,ORIG_CHN,Seller.Name,ORIG_RT,ORIG_AMT,ORIG_TRM,ORIG_DTE,FRST_DTE,OLTV,OCLTV,...,NUM_UNIT,OCC_STAT,STATE,ZIP_3,MI_PCT,Product.Type,CSCORE_C,MI_TYPE,RELOCATION_FLG,FCC
17718,149180644668,R,"BANK OF AMERICA, N.A.",4.875,117000,360,01/2010,03/2010,88,88.0,...,1,P,TX,778,25.0,FRM,794.0,1.0,N,False

Combining Performance and Acquisitions dataframe around 'Loan_Id'

In [19]:
Delq  = performance_df.set_index("LOAN_ID")["Delq.Status"].to_dict()

acquisition_df["Delq.Status"] = acquisition_df["LOAN_ID"].map(Delq)
holder = acquisition_df["Delq.Status"].notna()
acquisition_df_trim = acquisition_df[holder]

In [20]:
acquisition_df_trim

,LOAN_ID,ORIG_CHN,Seller.Name,ORIG_RT,ORIG_AMT,ORIG_TRM,ORIG_DTE,FRST_DTE,OLTV,OCLTV,...,OCC_STAT,STATE,ZIP_3,MI_PCT,Product.Type,CSCORE_C,MI_TYPE,RELOCATION_FLG,FCC,Delq.Status
0,100010079393,C,"WELLS FARGO BANK, N.A.",4.875,284000,360,01/2010,03/2010,80,80.0,...,P,TX,787,NaN,FRM,NaN,NaN,N,False,X
1,100013622306,R,"JPMORGAN CHASE BANK, NATIONAL ASSOCIATION",4.750,87000,180,12/2009,02/2010,63,63.0,...,P,CA,932,NaN,FRM,785.0,NaN,N,False,0
2,100019943199,R,OTHER,5.000,417000,360,11/2009,01/2010,43,43.0,...,S,FL,342,NaN,FRM,808.0,NaN,N,False,X
3,100022098429,R,OTHER,5.250,461000,360,01/2010,03/2010,61,61.0,...,P,NY,112,NaN,FRM,NaN,NaN,N,False,0
4,100023088745,R,"WELLS FARGO BANK, N.A.",5.250,100000,360,11/2009,01/2010,80,80.0,...,P,OH,446,NaN,FRM,NaN,NaN,N,False,X
5,100027393681,B,"CITIMORTGAGE, INC.",4.250,274000,120,01/2010,03/2010,65,82.0,...,P,CA,913,NaN,FRM,NaN,NaN,N,False,X
6,100027760956,R,OTHER,5.250,227000,360,01/2010,03/2010,55,55.0,...,P,CA,934,NaN,FRM,799.0,NaN,N,False,X
7,100031032487,R,"BANK OF AMERICA, N.A.",5.125,730000,360,03/2010,04/2010,63,63.0,...,P,MD,208,NaN,FRM,NaN,NaN,N,False,X
8,100032715932,R,SUNTRUST MORTGAGE INC.,5.375,96000,360,12/2009,01/2010,75,75.0,...,I,LA,711,NaN,FRM,815.0,NaN,N,False,X
9,100033339771,R,OTHER,5.250,300000,360,02/2010,04/2010,74,74.0,...,P,ID,836,NaN,FRM,NaN,NaN,N,False,X
10,100036162795,R,"WELLS FARGO BANK, N.A.",4.625,200000,180,12/2009,02/2010,39,39.0,...,P,MD,217,NaN,FRM,NaN,NaN,N,False,X
11,100039757358,C,"CITIMORTGAGE, INC.",4.625,228000,360,12/2009,02/2010,37,37.0,...,P,CA,902,NaN,FRM,781.0,NaN,N,False,X
12,100040783841,C,"CITIMORTGAGE, INC.",4.750,257000,360,01/2010,03/2010,52,52.0,...,P,UT,846,NaN,FRM,721.0,NaN,N,False,0
13,100044567305,C,OTHER,4.875,98000,360,01/2010,03/2010,54,54.0,...,S,WI,549,NaN,FRM,775.0,NaN,N,False,X
14,100046088905,C,"BANK OF AMERICA, N.A.",4.750,279000,360,12/2009,02/2010,64,64.0,...,P,CA,960,NaN,FRM,822.0,NaN,N,False,X
15,100049953168,B,"BANK OF AMERICA, N.A.",5.250,292000,360,01/2010,03/2010,80,80.0,...,P,NY,115,NaN,FRM,NaN,NaN,N,False,1
16,100054405732,B,"BANK OF AMERICA, N.A.",4.875,350000,360,12/2009,02/2010,65,65.0,...,P,TX,787,NaN,FRM,793.0,NaN,N,False,X
17,100056029701,C,"WELLS FARGO BANK, N.A.",4.250,103000,180,12/2009,02/2010,80,80.0,...,P,MO,630,NaN,FRM,NaN,NaN,N,False,X
18,100056508170,R,"WELLS FARGO BANK, N.A.",5.000,141000,360,12/2009,03/2010,69,69.0,...,P,DC,200,NaN,FRM,NaN,NaN,N,False,0
19,100056554242,C,"WELLS FARGO BANK, N.A.",4.375,300000,180,12/2009,02/2010,43,43.0,...,P,KY,400,NaN,FRM,792.0,NaN,N,False,X
20,100056793679,R,OTHER,5.625,95000,360,02/2010,04/2010,80,80.0,...,P,PA,171,NaN,FRM,NaN,NaN,N,False,X
21,100057102292,R,OTHER,5.125,109000,240,01/2010,03/2010,80,80.0,...,P,GA,317,NaN,FRM,NaN,NaN,N,False,0
22,100061403984,C,"JPMORGAN CHASE BANK, NATIONAL ASSOCIATION",5.125,660000,360,01/2010,03/2010,80,80.0,...,P,CT,68,NaN,FRM,775.0,NaN,N,False,X
23,100064110478,B,OTHER,5.625,128000,360,03/2010,05/2010,75,75.0,...,I,TX,752,NaN,FRM,NaN,NaN,N,False,X
24,100064988434,R,"WELLS FARGO BANK, N.A.",4.875,300000,360,01/2010,03/2010,43,43.0,...,S,AZ,852,NaN,FRM,NaN,NaN,N,False,X
25,100067986742,C,"BANK OF AMERICA, N.A.",4.375,345000,360,01/2010,03/2010,77,77.0,...,P,CO,800,NaN,FRM,797.0,NaN,N,False,0
26,100075990168,R,OTHER,4.500,127000,180,12/2009,02/2010,73,73.0,...,P,MI,480,NaN,FRM,NaN,NaN,N,False,X
27,100080406480,C,U.S. BANK N.A.,5.375,400000,360,01/2010,03/2010,53,53.0,...,P,UT,840,NaN,FRM,NaN,NaN,N,False,X
28,100080816876,R,OTHER,4.875,32000,240,01/2010,03/2010,80,80.0,...,P,TN,380,NaN,FRM,NaN,NaN,N,False,0
29,100084613192,B,"BANK OF AMERICA, N.A.",4.375,295000,180,12/2009,03/2010,65,65.0,...,P,MA,17,NaN,FRM,760.0,NaN,N,False,X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17688,149081337012,R,"JPMORGAN CHASE BANK, NATIONAL ASSOCIATION",5.250,249000,360,11/2009,02/2010,65,65.0,...,P,NY,117,NaN,FRM,NaN,NaN,N,False,X
17689,149091240659,R,OTHER,4.750,417000,360,12/2009,02/2010,17,42.0,...,P,WA,980,NaN,FRM,780.0,NaN,N,False,X
17690,149093814297,R,"WELLS FARGO BANK, N.A.",4.875,237000,360,02/2010,04/2010,71,71.0,...,P,SC,294,NaN,FRM,NaN,NaN,N,False,X
17691,149097803154,R,FLAGSTAR CAPITAL MARKETS CORPORATION,6.250,100000,360,12/2009,02/2010,76,76.0,...,P,TX,787,NaN,FRM,NaN,NaN,N,False,X
17692,149101005733,B,"WELLS FARGO BANK, N.A.",5.250,142000,360,12/2009,02/2010,90,90.0,...,P,KS,662,25.0,FRM,NaN,1.0,N,False,X
17693,149104482849,C,"BANK OF AMERICA, N.A.",4.625,150000,180,12/2009,02/2010,77,77.0,...,P,IL,606,NaN,FRM,754.0,NaN,N,False,X
17694,149104877642,B,OTHER,5.250,217000,360,02/2010,04/2010,70,70.0,...,P,CA,913,NaN,FRM,NaN,NaN,N,False,X
17695,149105435514,C,"WELLS FARGO BANK, N.A.",4.875,209000,360,12/2009,02/2010,80,80.0,...,P,IL,600,NaN,FRM,758.0,NaN,N,False,0
17697,149113864430,C,"CITIMORTGAGE, INC.",4.250,189000,120,11/2009,01/2010,44,44.0,...,P,NJ,85,NaN,FRM,791.0,NaN,N,False,0
17698,149126798332,R,OTHER,5.250,311000,360,01/2010,03/2010,75,75.0,...,I,AZ,853,NaN,FRM,743.0,NaN,N,False,X
17699,149132541599,C,"GMAC MORTGAGE, LLC",4.375,217000,180,12/2009,02/2010,20,21.0,...,P,CA,950,NaN,FRM,745.0,NaN,N,False,X
17700,149134717764,R,"WELLS FARGO BANK, N.A.",5.000,190000,360,01/2010,02/2010,80,80.0,...,P,AR,723,NaN,FRM,NaN,NaN,N,False,X
17701,149138031580,C,"WELLS FARGO BANK, N.A.",4.625,110000,180,12/2009,02/2010,55,55.0,...,P,WI,531,NaN,FRM,737.0,NaN,N,False,X
17702,149142918034,C,PHH MORTGAGE CORPORATION,5.000,90000,360,01/2010,03/2010,95,95.0,...,P,NY,136,35.0,FRM,727.0,1.0,N,False,0
17703,149142995044,R,OTHER,5.375,200000,360,01/2010,03/2010,70,70.0,...,P,MS,391,NaN,FRM,759.0,NaN,N,False,X
17704,149144004546,C,"GMAC MORTGAGE, LLC",4.750,230000,240,12/2009,02/2010,80,80.0,...,P,IL,605,NaN,FRM,801.0,NaN,N,False,X
17705,149145441898,C,"BANK OF AMERICA, N.A.",5.000,255000,360,12/2009,02/2010,78,78.0,...,S,AL,356,NaN,FRM,811.0,NaN,N,False,X
17706,149147001780,C,"BANK OF AMERICA, N.A.",4.500,49000,180,01/2010,03/2010,36,36.0,...,P,IL,617,NaN,FRM,NaN,NaN,N,False,X
17707,149147918087,C,"WELLS FARGO BANK, N.A.",5.250,245000,360,11/2009,01/2010,75,75.0,...,P,CA,908,NaN,FRM,724.0,NaN,N,False,X
17708,149156258852,C,"BANK OF AMERICA, N.A.",4.875,256000,360,11/2009,01/2010,80,80.0,...,P,CO,800,NaN,FRM,NaN,NaN,N,False,X
17709,149162653642,C,"JPMORGAN CHASE BANK, NATIONAL ASSOCIATION",4.250,220000,180,12/2009,02/2010,54,54.0,...,P,CT,64,NaN,FRM,803.0,NaN,N,False,X
17710,149166823928,C,"BANK OF AMERICA, N.A.",4.875,72000,360,12/2009,02/2010,22,22.0,...,P,MD,210,NaN,FRM,802.0,NaN,N,False,X
17711,149169458956,C,"BANK OF AMERICA, N.A.",5.000,370000,360,01/2010,03/2010,56,56.0,...,P,CA,928,NaN,FRM,751.0,NaN,N,False,X
17712,149170823980,C,"WELLS FARGO BANK, N.A.",5.000,204000,360,12/2009,02/2010,80,80.0,...,P,TX,750,NaN,FRM,NaN,NaN,N,False,X
17713,149171575167,R,OTHER,4.875,105000,360,01/2010,03/2010,80,80.0,...,P,CT,64,NaN,FRM,NaN,NaN,N,False,1
17714,149175953968,B,OTHER,5.500,72000,360,02/2010,04/2010,75,75.0,...,P,IL,600,NaN,FRM,NaN,NaN,N,False,0
17715,149177183663,R,"WELLS FARGO BANK, N.A.",4.375,310000,180,01/2010,04/2010,64,64.0,...,P,WI,531,NaN,FRM,NaN,NaN,N,False,X
17716,149179931784,R,OTHER,4.375,150000,180,12/2009,03/2010,21,21.0,...,P,NJ,77,NaN,FRM,NaN,NaN,N,False,X
17717,149179972416,R,OTHER,5.250,142000,360,02/2010,04/2010,80,94.0,...,P,NY,146,NaN,FRM,727.0,NaN,N,False,X
17718,149180644668,R,"BANK OF AMERICA, N.A.",4.875,117000,360,01/2010,03/2010,88,88.0,...,P,TX,778,25.0,FRM,794.0,1.0,N,False,0

In [45]:
acquisition_df_trim.shape

(17622, 27)

PART(c)- Modifying Acquisitions Dataframe to include elements with non-zero Delinquency Status

In [46]:
acquisition_df_trim.loc[acquisition_df_trim["Delq.Status"] != '0']

,LOAN_ID,ORIG_CHN,Seller.Name,ORIG_RT,ORIG_AMT,ORIG_TRM,ORIG_DTE,FRST_DTE,OLTV,OCLTV,...,OCC_STAT,STATE,ZIP_3,MI_PCT,Product.Type,CSCORE_C,MI_TYPE,RELOCATION_FLG,FCC,Delq.Status
0,100010079393,C,"WELLS FARGO BANK, N.A.",4.875,284000,360,01/2010,03/2010,80,80.0,...,P,TX,787,NaN,FRM,NaN,NaN,N,False,X
2,100019943199,R,OTHER,5.000,417000,360,11/2009,01/2010,43,43.0,...,S,FL,342,NaN,FRM,808.0,NaN,N,False,X
4,100023088745,R,"WELLS FARGO BANK, N.A.",5.250,100000,360,11/2009,01/2010,80,80.0,...,P,OH,446,NaN,FRM,NaN,NaN,N,False,X
5,100027393681,B,"CITIMORTGAGE, INC.",4.250,274000,120,01/2010,03/2010,65,82.0,...,P,CA,913,NaN,FRM,NaN,NaN,N,False,X
6,100027760956,R,OTHER,5.250,227000,360,01/2010,03/2010,55,55.0,...,P,CA,934,NaN,FRM,799.0,NaN,N,False,X
7,100031032487,R,"BANK OF AMERICA, N.A.",5.125,730000,360,03/2010,04/2010,63,63.0,...,P,MD,208,NaN,FRM,NaN,NaN,N,False,X
8,100032715932,R,SUNTRUST MORTGAGE INC.,5.375,96000,360,12/2009,01/2010,75,75.0,...,I,LA,711,NaN,FRM,815.0,NaN,N,False,X
9,100033339771,R,OTHER,5.250,300000,360,02/2010,04/2010,74,74.0,...,P,ID,836,NaN,FRM,NaN,NaN,N,False,X
10,100036162795,R,"WELLS FARGO BANK, N.A.",4.625,200000,180,12/2009,02/2010,39,39.0,...,P,MD,217,NaN,FRM,NaN,NaN,N,False,X
11,100039757358,C,"CITIMORTGAGE, INC.",4.625,228000,360,12/2009,02/2010,37,37.0,...,P,CA,902,NaN,FRM,781.0,NaN,N,False,X
13,100044567305,C,OTHER,4.875,98000,360,01/2010,03/2010,54,54.0,...,S,WI,549,NaN,FRM,775.0,NaN,N,False,X
14,100046088905,C,"BANK OF AMERICA, N.A.",4.750,279000,360,12/2009,02/2010,64,64.0,...,P,CA,960,NaN,FRM,822.0,NaN,N,False,X
15,100049953168,B,"BANK OF AMERICA, N.A.",5.250,292000,360,01/2010,03/2010,80,80.0,...,P,NY,115,NaN,FRM,NaN,NaN,N,False,1
16,100054405732,B,"BANK OF AMERICA, N.A.",4.875,350000,360,12/2009,02/2010,65,65.0,...,P,TX,787,NaN,FRM,793.0,NaN,N,False,X
17,100056029701,C,"WELLS FARGO BANK, N.A.",4.250,103000,180,12/2009,02/2010,80,80.0,...,P,MO,630,NaN,FRM,NaN,NaN,N,False,X
19,100056554242,C,"WELLS FARGO BANK, N.A.",4.375,300000,180,12/2009,02/2010,43,43.0,...,P,KY,400,NaN,FRM,792.0,NaN,N,False,X
20,100056793679,R,OTHER,5.625,95000,360,02/2010,04/2010,80,80.0,...,P,PA,171,NaN,FRM,NaN,NaN,N,False,X
22,100061403984,C,"JPMORGAN CHASE BANK, NATIONAL ASSOCIATION",5.125,660000,360,01/2010,03/2010,80,80.0,...,P,CT,68,NaN,FRM,775.0,NaN,N,False,X
23,100064110478,B,OTHER,5.625,128000,360,03/2010,05/2010,75,75.0,...,I,TX,752,NaN,FRM,NaN,NaN,N,False,X
24,100064988434,R,"WELLS FARGO BANK, N.A.",4.875,300000,360,01/2010,03/2010,43,43.0,...,S,AZ,852,NaN,FRM,NaN,NaN,N,False,X
26,100075990168,R,OTHER,4.500,127000,180,12/2009,02/2010,73,73.0,...,P,MI,480,NaN,FRM,NaN,NaN,N,False,X
27,100080406480,C,U.S. BANK N.A.,5.375,400000,360,01/2010,03/2010,53,53.0,...,P,UT,840,NaN,FRM,NaN,NaN,N,False,X
29,100084613192,B,"BANK OF AMERICA, N.A.",4.375,295000,180,12/2009,03/2010,65,65.0,...,P,MA,17,NaN,FRM,760.0,NaN,N,False,X
30,100087041048,R,"WELLS FARGO BANK, N.A.",5.875,100000,360,02/2010,04/2010,95,95.0,...,P,CO,802,30.0,FRM,761.0,1.0,N,False,X
31,100091653134,R,OTHER,5.375,312000,360,12/2009,02/2010,80,80.0,...,P,WV,265,NaN,FRM,NaN,NaN,N,False,1
33,100106628052,R,"WELLS FARGO BANK, N.A.",4.875,226000,360,01/2010,03/2010,80,80.0,...,P,TX,770,NaN,FRM,NaN,NaN,Y,False,X
35,100108873379,B,OTHER,4.875,255000,360,12/2009,02/2010,47,47.0,...,P,CA,902,NaN,FRM,NaN,NaN,N,False,X
36,100110766674,C,FLAGSTAR CAPITAL MARKETS CORPORATION,5.250,256000,360,12/2009,02/2010,80,80.0,...,P,TX,786,NaN,FRM,725.0,NaN,N,False,X
37,100111243794,R,OTHER,5.500,85000,360,02/2010,04/2010,34,34.0,...,I,PR,9,NaN,FRM,NaN,NaN,N,False,X
38,100111334256,R,OTHER,5.500,71000,360,01/2010,03/2010,75,75.0,...,S,WI,542,NaN,FRM,753.0,NaN,N,False,X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17680,149053378214,C,U.S. BANK N.A.,4.875,416000,360,12/2009,02/2010,80,87.0,...,P,TX,770,NaN,FRM,NaN,NaN,N,False,X
17681,149054334688,R,"CITIMORTGAGE, INC.",5.375,86000,360,12/2009,02/2010,62,62.0,...,S,PA,184,NaN,FRM,712.0,NaN,N,False,X
17682,149061282820,R,U.S. BANK N.A.,5.000,115000,360,11/2009,01/2010,73,73.0,...,P,MO,631,NaN,FRM,NaN,NaN,N,False,X
17686,149074769227,R,"WELLS FARGO BANK, N.A.",4.375,185000,180,12/2009,02/2010,65,85.0,...,P,MT,594,NaN,FRM,796.0,NaN,N,False,X
17687,149078530579,C,OTHER,5.000,168000,360,12/2009,02/2010,80,80.0,...,P,IL,616,NaN,FRM,730.0,NaN,N,False,X
17688,149081337012,R,"JPMORGAN CHASE BANK, NATIONAL ASSOCIATION",5.250,249000,360,11/2009,02/2010,65,65.0,...,P,NY,117,NaN,FRM,NaN,NaN,N,False,X
17689,149091240659,R,OTHER,4.750,417000,360,12/2009,02/2010,17,42.0,...,P,WA,980,NaN,FRM,780.0,NaN,N,False,X
17690,149093814297,R,"WELLS FARGO BANK, N.A.",4.875,237000,360,02/2010,04/2010,71,71.0,...,P,SC,294,NaN,FRM,NaN,NaN,N,False,X
17691,149097803154,R,FLAGSTAR CAPITAL MARKETS CORPORATION,6.250,100000,360,12/2009,02/2010,76,76.0,...,P,TX,787,NaN,FRM,NaN,NaN,N,False,X
17692,149101005733,B,"WELLS FARGO BANK, N.A.",5.250,142000,360,12/2009,02/2010,90,90.0,...,P,KS,662,25.0,FRM,NaN,1.0,N,False,X
17693,149104482849,C,"BANK OF AMERICA, N.A.",4.625,150000,180,12/2009,02/2010,77,77.0,...,P,IL,606,NaN,FRM,754.0,NaN,N,False,X
17694,149104877642,B,OTHER,5.250,217000,360,02/2010,04/2010,70,70.0,...,P,CA,913,NaN,FRM,NaN,NaN,N,False,X
17698,149126798332,R,OTHER,5.250,311000,360,01/2010,03/2010,75,75.0,...,I,AZ,853,NaN,FRM,743.0,NaN,N,False,X
17699,149132541599,C,"GMAC MORTGAGE, LLC",4.375,217000,180,12/2009,02/2010,20,21.0,...,P,CA,950,NaN,FRM,745.0,NaN,N,False,X
17700,149134717764,R,"WELLS FARGO BANK, N.A.",5.000,190000,360,01/2010,02/2010,80,80.0,...,P,AR,723,NaN,FRM,NaN,NaN,N,False,X
17701,149138031580,C,"WELLS FARGO BANK, N.A.",4.625,110000,180,12/2009,02/2010,55,55.0,...,P,WI,531,NaN,FRM,737.0,NaN,N,False,X
17703,149142995044,R,OTHER,5.375,200000,360,01/2010,03/2010,70,70.0,...,P,MS,391,NaN,FRM,759.0,NaN,N,False,X
17704,149144004546,C,"GMAC MORTGAGE, LLC",4.750,230000,240,12/2009,02/2010,80,80.0,...,P,IL,605,NaN,FRM,801.0,NaN,N,False,X
17705,149145441898,C,"BANK OF AMERICA, N.A.",5.000,255000,360,12/2009,02/2010,78,78.0,...,S,AL,356,NaN,FRM,811.0,NaN,N,False,X
17706,149147001780,C,"BANK OF AMERICA, N.A.",4.500,49000,180,01/2010,03/2010,36,36.0,...,P,IL,617,NaN,FRM,NaN,NaN,N,False,X
17707,149147918087,C,"WELLS FARGO BANK, N.A.",5.250,245000,360,11/2009,01/2010,75,75.0,...,P,CA,908,NaN,FRM,724.0,NaN,N,False,X
17708,149156258852,C,"BANK OF AMERICA, N.A.",4.875,256000,360,11/2009,01/2010,80,80.0,...,P,CO,800,NaN,FRM,NaN,NaN,N,False,X
17709,149162653642,C,"JPMORGAN CHASE BANK, NATIONAL ASSOCIATION",4.250,220000,180,12/2009,02/2010,54,54.0,...,P,CT,64,NaN,FRM,803.0,NaN,N,False,X
17710,149166823928,C,"BANK OF AMERICA, N.A.",4.875,72000,360,12/2009,02/2010,22,22.0,...,P,MD,210,NaN,FRM,802.0,NaN,N,False,X
17711,149169458956,C,"BANK OF AMERICA, N.A.",5.000,370000,360,01/2010,03/2010,56,56.0,...,P,CA,928,NaN,FRM,751.0,NaN,N,False,X
17712,149170823980,C,"WELLS FARGO BANK, N.A.",5.000,204000,360,12/2009,02/2010,80,80.0,...,P,TX,750,NaN,FRM,NaN,NaN,N,False,X
17713,149171575167,R,OTHER,4.875,105000,360,01/2010,03/2010,80,80.0,...,P,CT,64,NaN,FRM,NaN,NaN,N,False,1
17715,149177183663,R,"WELLS FARGO BANK, N.A.",4.375,310000,180,01/2010,04/2010,64,64.0,...,P,WI,531,NaN,FRM,NaN,NaN,N,False,X
17716,149179931784,R,OTHER,4.375,150000,180,12/2009,03/2010,21,21.0,...,P,NJ,77,NaN,FRM,NaN,NaN,N,False,X
17717,149179972416,R,OTHER,5.250,142000,360,02/2010,04/2010,80,94.0,...,P,NY,146,NaN,FRM,727.0,NaN,N,False,X